### ISSUE TITLE
list index out of range in data process stage

### ISSUE THREAD

**Issue by bardia13** [masjohncook/CREMEv2#36]
Hi
When running the testbed (either in default configuration or just simulating a single attack), I am getting a list index out-of-range error in the data process stage, which results in the testbed failing. I have attached the error as well. I did try this on another system and still got the same results. Do you have any idea what causes this? It happens in the syslog part of the data process stage.
<img width="1353" alt="Screenshot 2023-02-06 at 11 51 44 PM" src="https://user-images.githubusercontent.com/13238840/217169576-277baf71-19ad-4c67-b7a3-6306e005a59f.png">

**Comment by bardia13** [comment]
I checked a bit more, and apparently, in the disk wipe, for example, It is getting the "Session ID (3) not found" error.  I got the same error on other attacks as well.

**Comment by masjohncook** [comment]
Hi Bardia, 

We already fixed the index file out of range. For the session ID yes you will get the error because the command just tests the session created when attacking the target. But we still also patch the attack part.

Thank's

**Comment by bardia13** [comment]
I am using the latest version on the main branch, and I am still getting the index out of range. Am I doing something wrong?

By the way, thanks for the fast responses. :)

**Comment by masjohncook** [comment]
Hi Bardia,

sorry, we did a mistake. You can pull the main branch again.
